import Foundation
import FirebaseAuth
import FirebaseFirestore

struct UpcomingDate: Identifiable {
    let id: String
    let title: String
    let date: Date
    let emoji: String
    let daysUntil: Int
    let isAutoGenerated: Bool
}

@Observable
final class OurStoryService {
    var significantDates: [SignificantDate] = []
    var errorMessage: String?
    var isLoading = false

    private var listener: ListenerRegistration?
    private var currentPairId: String?
    private var db: Firestore { Firestore.firestore() }

    deinit {
        listener?.remove()
    }

    // MARK: - Listener

    func startListening(pairId: String) {
        stopListening()
        currentPairId = pairId

        listener = db.collection(Constants.Firestore.pairsCollection)
            .document(pairId)
            .collection(Constants.OurStory.significantDatesCollection)
            .order(by: "date", descending: false)
            .addSnapshotListener { [weak self] snapshot, error in
                guard let snapshot else {
                    self?.errorMessage = error?.localizedDescription
                    return
                }
                self?.significantDates = snapshot.documents.compactMap { try? $0.data(as: SignificantDate.self) }
            }
    }

    func stopListening() {
        listener?.remove()
        listener = nil
        significantDates = []
        currentPairId = nil
    }

    // MARK: - CRUD

    func addSignificantDate(title: String, date: Date, emoji: String?, recurring: Bool) {
        guard let pairId = currentPairId,
              let uid = Auth.auth().currentUser?.uid else { return }

        let sigDate = SignificantDate(
            title: title,
            date: date,
            emoji: emoji,
            recurring: recurring,
            addedBy: uid,
            createdAt: Date()
        )

        Task {
            do {
                let colRef = db.collection(Constants.Firestore.pairsCollection)
                    .document(pairId)
                    .collection(Constants.OurStory.significantDatesCollection)
                try colRef.addDocument(from: sigDate)
            } catch {
                await MainActor.run {
                    self.errorMessage = error.localizedDescription
                }
            }
        }
    }

    func updateSignificantDate(dateId: String, title: String, date: Date, emoji: String?, recurring: Bool) {
        guard let pairId = currentPairId else { return }

        Task {
            do {
                try await db.collection(Constants.Firestore.pairsCollection)
                    .document(pairId)
                    .collection(Constants.OurStory.significantDatesCollection)
                    .document(dateId)
                    .updateData([
                        "title": title,
                        "date": Timestamp(date: date),
                        "emoji": emoji as Any,
                        "recurring": recurring
                    ])
            } catch {
                await MainActor.run {
                    self.errorMessage = error.localizedDescription
                }
            }
        }
    }

    func deleteSignificantDate(dateId: String) {
        guard let pairId = currentPairId else { return }

        Task {
            do {
                try await db.collection(Constants.Firestore.pairsCollection)
                    .document(pairId)
                    .collection(Constants.OurStory.significantDatesCollection)
                    .document(dateId)
                    .delete()
            } catch {
                await MainActor.run {
                    self.errorMessage = error.localizedDescription
                }
            }
        }
    }

    // MARK: - Anniversary

    func setAnniversary(date: Date) {
        guard let pairId = currentPairId else { return }

        Task {
            do {
                try await db.collection(Constants.Firestore.pairsCollection)
                    .document(pairId)
                    .updateData(["anniversary": Timestamp(date: date)])
            } catch {
                await MainActor.run {
                    self.errorMessage = error.localizedDescription
                }
            }
        }
    }

    // MARK: - Upcoming Dates

    func upcomingDates(anniversary: Date?, calendarEvents: [CalendarEvent] = []) -> [UpcomingDate] {
        let calendar = Calendar.current
        let today = calendar.startOfDay(for: Date())
        var results: [UpcomingDate] = []

        // Anniversary
        if let anniversary {
            if let next = nextOccurrence(of: anniversary, after: today, calendar: calendar) {
                let days = calendar.dateComponents([.day], from: today, to: next).day ?? 0
                results.append(UpcomingDate(
                    id: "anniversary",
                    title: "Anniversary",
                    date: next,
                    emoji: "💕",
                    daysUntil: days,
                    isAutoGenerated: true
                ))
            }
        }

        // Valentine's Day — Feb 14
        if let valentines = nextFixedDate(month: 2, day: 14, after: today, calendar: calendar) {
            let days = calendar.dateComponents([.day], from: today, to: valentines).day ?? 0
            results.append(UpcomingDate(
                id: "valentines",
                title: "Valentine's Day",
                date: valentines,
                emoji: "❤️",
                daysUntil: days,
                isAutoGenerated: true
            ))
        }

        // Christmas — Dec 25
        if let christmas = nextFixedDate(month: 12, day: 25, after: today, calendar: calendar) {
            let days = calendar.dateComponents([.day], from: today, to: christmas).day ?? 0
            results.append(UpcomingDate(
                id: "christmas",
                title: "Christmas",
                date: christmas,
                emoji: "🎄",
                daysUntil: days,
                isAutoGenerated: true
            ))
        }

        // Custom significant dates
        for sigDate in significantDates {
            let targetDate: Date?
            if sigDate.recurring {
                targetDate = nextOccurrence(of: sigDate.date, after: today, calendar: calendar)
            } else {
                let sigDay = calendar.startOfDay(for: sigDate.date)
                targetDate = sigDay >= today ? sigDay : nil
            }

            if let target = targetDate {
                let days = calendar.dateComponents([.day], from: today, to: target).day ?? 0
                results.append(UpcomingDate(
                    id: sigDate.id ?? UUID().uuidString,
                    title: sigDate.title,
                    date: target,
                    emoji: sigDate.emoji ?? "📅",
                    daysUntil: days,
                    isAutoGenerated: false
                ))
            }
        }

        // Accepted calendar events
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        for event in calendarEvents where event.status == .accepted {
            guard let startDate = dateFormatter.date(from: event.startDate) else { continue }
            let eventDay = calendar.startOfDay(for: startDate)
            guard eventDay >= today else { continue }
            let days = calendar.dateComponents([.day], from: today, to: eventDay).day ?? 0
            results.append(UpcomingDate(
                id: event.id ?? UUID().uuidString,
                title: event.title,
                date: eventDay,
                emoji: "📆",
                daysUntil: days,
                isAutoGenerated: true
            ))
        }

        return results.sorted { $0.daysUntil < $1.daysUntil }
    }

    // MARK: - Helpers

    private func nextOccurrence(of date: Date, after today: Date, calendar: Calendar) -> Date? {
        let components = calendar.dateComponents([.month, .day], from: date)
        guard let month = components.month, let day = components.day else { return nil }
        return nextFixedDate(month: month, day: day, after: today, calendar: calendar)
    }

    private func nextFixedDate(month: Int, day: Int, after today: Date, calendar: Calendar) -> Date? {
        let year = calendar.component(.year, from: today)
        var comps = DateComponents(year: year, month: month, day: day)
        if let candidate = calendar.date(from: comps), calendar.startOfDay(for: candidate) >= today {
            return calendar.startOfDay(for: candidate)
        }
        comps.year = year + 1
        return calendar.date(from: comps).map { calendar.startOfDay(for: $0) }
    }
}
