import Foundation

struct UpcomingDate: Identifiable {
    let id: String
    let title: String
    let date: Date
    let emoji: String
    let daysUntil: Int
    let isAutoGenerated: Bool
    let isCalendarEvent: Bool

    init(id: String, title: String, date: Date, emoji: String, daysUntil: Int, isAutoGenerated: Bool, isCalendarEvent: Bool = false) {
        self.id = id
        self.title = title
        self.date = date
        self.emoji = emoji
        self.daysUntil = daysUntil
        self.isAutoGenerated = isAutoGenerated
        self.isCalendarEvent = isCalendarEvent
    }
}

@Observable
final class OurStoryService {
    var significantDates: [SignificantDate] = []
    var errorMessage: String?
    var isLoading = false

    private var currentPairId: String?

    // MARK: - Listener

    func startListening(pairId: String) {
        stopListening()
        currentPairId = pairId

        Task {
            do {
                let loaded: [SignificantDate] = try await APIClient.shared.get("/pairs/\(pairId)/significant-dates")
                await MainActor.run { self.significantDates = loaded }
            } catch {
                await MainActor.run { self.errorMessage = error.localizedDescription }
            }
        }

        WebSocketManager.shared.on("significant-date:created") { [weak self] (sd: SignificantDate) in
            self?.significantDates.append(sd)
        }
        WebSocketManager.shared.on("significant-date:updated") { [weak self] (sd: SignificantDate) in
            if let i = self?.significantDates.firstIndex(where: { $0.id == sd.id }) {
                self?.significantDates[i] = sd
            }
        }
        WebSocketManager.shared.on("significant-date:deleted") { [weak self] (payload: DeletePayload) in
            self?.significantDates.removeAll { $0.id == payload.id }
        }
    }

    func stopListening() {
        significantDates = []
        currentPairId = nil
    }

    // MARK: - CRUD

    func addSignificantDate(title: String, date: Date, emoji: String?, recurring: Bool) {
        guard let pairId = currentPairId else { return }

        let dateStr = DateFormatter.yyyyMMdd.string(from: date)

        Task {
            do {
                let body = CreateSigDateBody(title: title, date: dateStr, emoji: emoji, recurring: recurring)
                let _: SignificantDate = try await APIClient.shared.post("/pairs/\(pairId)/significant-dates", body: body)
            } catch {
                await MainActor.run { self.errorMessage = error.localizedDescription }
            }
        }
    }

    func updateSignificantDate(dateId: String, title: String, date: Date, emoji: String?, recurring: Bool) {
        guard let pairId = currentPairId else { return }

        let dateStr = DateFormatter.yyyyMMdd.string(from: date)

        Task {
            do {
                let body = UpdateSigDateBody(title: title, date: dateStr, emoji: emoji, recurring: recurring)
                let _: SignificantDate = try await APIClient.shared.patch("/pairs/\(pairId)/significant-dates/\(dateId)", body: body)
            } catch {
                await MainActor.run { self.errorMessage = error.localizedDescription }
            }
        }
    }

    func deleteSignificantDate(dateId: String) {
        guard let pairId = currentPairId else { return }

        Task {
            do {
                try await APIClient.shared.delete("/pairs/\(pairId)/significant-dates/\(dateId)")
            } catch {
                await MainActor.run { self.errorMessage = error.localizedDescription }
            }
        }
    }

    // MARK: - Anniversary

    func setAnniversary(date: Date) {
        guard let pairId = currentPairId else { return }

        let dateStr = DateFormatter.yyyyMMdd.string(from: date)

        Task {
            do {
                let body = UpdateAnniversaryBody(anniversary: dateStr)
                let _: Pair = try await APIClient.shared.patch("/pairs/\(pairId)", body: body)
            } catch {
                await MainActor.run { self.errorMessage = error.localizedDescription }
            }
        }
    }

    // MARK: - Upcoming Dates

    func upcomingDates(anniversary: Date?, calendarEvents: [CalendarEvent] = []) -> [UpcomingDate] {
        let calendar = Calendar.current
        let today = calendar.startOfDay(for: Date())
        var results: [UpcomingDate] = []

        if let anniversary {
            if let next = nextOccurrence(of: anniversary, after: today, calendar: calendar) {
                let days = calendar.dateComponents([.day], from: today, to: next).day ?? 0
                results.append(UpcomingDate(id: "anniversary", title: "Anniversary", date: next, emoji: "💕", daysUntil: days, isAutoGenerated: true))
            }
        }

        if let valentines = nextFixedDate(month: 2, day: 14, after: today, calendar: calendar) {
            let days = calendar.dateComponents([.day], from: today, to: valentines).day ?? 0
            results.append(UpcomingDate(id: "valentines", title: "Valentine's Day", date: valentines, emoji: "❤️", daysUntil: days, isAutoGenerated: true))
        }

        if let christmas = nextFixedDate(month: 12, day: 25, after: today, calendar: calendar) {
            let days = calendar.dateComponents([.day], from: today, to: christmas).day ?? 0
            results.append(UpcomingDate(id: "christmas", title: "Christmas", date: christmas, emoji: "🎄", daysUntil: days, isAutoGenerated: true))
        }

        for sigDate in significantDates {
            let targetDate: Date?
            if sigDate.recurring {
                targetDate = nextOccurrence(of: sigDate.date, after: today, calendar: calendar)
            } else {
                let sigDay = calendar.startOfDay(for: sigDate.date)
                targetDate = sigDay >= today ? sigDay : nil
            }
            if let target = targetDate {
                let days = calendar.dateComponents([.day], from: today, to: target).day ?? 0
                results.append(UpcomingDate(id: sigDate.id, title: sigDate.title, date: target, emoji: sigDate.emoji ?? "📅", daysUntil: days, isAutoGenerated: false))
            }
        }

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        for event in calendarEvents where event.status == .accepted {
            guard let startDate = dateFormatter.date(from: event.startDate) else { continue }
            let eventDay = calendar.startOfDay(for: startDate)
            guard eventDay >= today else { continue }
            let days = calendar.dateComponents([.day], from: today, to: eventDay).day ?? 0
            results.append(UpcomingDate(id: event.id, title: event.title, date: eventDay, emoji: "📆", daysUntil: days, isAutoGenerated: true, isCalendarEvent: true))
        }

        return results.sorted { $0.daysUntil < $1.daysUntil }
    }

    // MARK: - Helpers

    private func nextOccurrence(of date: Date, after today: Date, calendar: Calendar) -> Date? {
        let components = calendar.dateComponents([.month, .day], from: date)
        guard let month = components.month, let day = components.day else { return nil }
        return nextFixedDate(month: month, day: day, after: today, calendar: calendar)
    }

    private func nextFixedDate(month: Int, day: Int, after today: Date, calendar: Calendar) -> Date? {
        let year = calendar.component(.year, from: today)
        var comps = DateComponents(year: year, month: month, day: day)
        if let candidate = calendar.date(from: comps), calendar.startOfDay(for: candidate) >= today {
            return calendar.startOfDay(for: candidate)
        }
        comps.year = year + 1
        return calendar.date(from: comps).map { calendar.startOfDay(for: $0) }
    }
}

// MARK: - Request DTOs

private struct CreateSigDateBody: Encodable {
    let title: String
    let date: String
    let emoji: String?
    let recurring: Bool
}

private struct UpdateSigDateBody: Encodable {
    let title: String?
    let date: String?
    let emoji: String?
    let recurring: Bool?
}

private struct UpdateAnniversaryBody: Encodable {
    let anniversary: String
}
